{ hostParams, ... }:
{
  programs.hyprlock = {
    enable = true;

    settings = {
      general = {
        no_fade_in = true;
        no_fade_out = true;

        ## These were autogenerated by home manager before. Are they defaults?
        disable_loading_bar = false;
        grace = 0;
        hide_cursor = true;
        ignore_empty_input = false;
      };

      background = if builtins.hasAttr "wallpaper" hostParams then {
        monitor = "";
        path = "${hostParams.wallpaper}";

        ## These were autogenerated by home manager before. Are they defaults?
        color = "rgba(25, 20, 20, 1.0)";
        blur_size = 8;
        blur_passes = 0;
        noise = "0.011700";
        contrast = "0.891700";
        brightness = "0.817200";
        vibrancy = "0.168600";
        vibrancy_darkness = "0.050000";
      } else {};

      input-field = {
        size = "360, 50";
        outer_color = "rgb(24, 25, 38)";
        inner_color = "rgb(91, 96, 120)";
        font_color = "rgb(202, 211, 245)";
        halign = "center";
        valign = "center";

        ## These were autogenerated by home manager before. Are they defaults?
        monitor = "";
        outline_thickness = 3;
        dots_size = "0.330000";
        dots_spacing = "0.150000";
        dots_center = true;
        dots_rounding = -1;
        fade_on_empty = true;
        fade_timeout = 2000;
        placeholder_text = "<i>Input Password...</i>";
        hide_input = false;
        rounding = -1;
        shadow_passes = 0;
        shadow_size = 3;
        shadow_color = "rgba(0, 0, 0, 1.0)";
        shadow_boost = "1.200000";
        check_color = "rgb(204, 136, 34)";
        fail_color = "rgb(204, 34, 34)";
        fail_text = "<i>$FAIL</i>";
        fail_transition = 300;
        capslock_color = -1;
        numlock_color = -1;
        bothlock_color = -1;
        invert_numlock = false;
        swap_font_color = false;
        position = "0, -20";
      };

      label = {
        text = ''cmd[update:1000] echo "<span foreground='##ff2222'>$(date)</span>"'';
        color = "rgb(237, 135, 150)";
        font_size = 72;
        font_family = "FiraCode";
        halign = "center";
        valign = "center";

        ## These were autogenerated by home manager before. Are they defaults?
        monitor = "";
        text_align = "";
        rotate = "0.000000";
        shadow_passes = 0;
        shadow_size = 3;
        shadow_color = "rgba(0, 0, 0, 1.0)";
        shadow_boost = "1.200000";
        position = "0, 80";
      };
    };
  };
}
