{ config, lib, pkgs, ... }:
let
  cfg = config.nixcfg.programs.nerd-dictation;
  userParams = config.hostParams.user;

  nerd-dictation = pkgs.callPackage ../../../pkgs/nerd-dictation { };
  models = import ./models.nix;

  # Generate a Python config for nerd-dictation's `--config` flag. Currently
  # just strips phantom trailing words -- Vosk's rnnlm rescore, active on the
  # full en-us-0.22 model, tends to hallucinate a high-prior word (almost
  # always "the") at end-of-stream when the acoustic model sees silence.
  # Adding more logic here later (custom substitutions, abbreviations, etc.)
  # is straightforward -- extend `nerd_dictation_process`.
  userConfig =
    let
      pySet = xs:
        "{"
        + lib.concatStringsSep ", "
            (map (w: ''"${lib.toLower w}"'') xs)
        + "}";
      blacklistPython = pySet cfg.trailingWordBlacklist;
      questionStartersPython = pySet cfg.questionStarters;
      addLeadingSpaceLit   = if cfg.addLeadingSpace   then "True" else "False";
      addTrailingPeriodLit = if cfg.addTrailingPeriod then "True" else "False";
      questionHeuristicLit = if cfg.questionHeuristic then "True" else "False";
      verbalPunctuationLit = if cfg.verbalPunctuation then "True" else "False";
    in pkgs.writeText "nerd-dictation-config.py" ''
      # Auto-generated by modules/programs/nerd-dictation.
      # Options: trailingWordBlacklist, addLeadingSpace, addTrailingPeriod.
      #
      # Pipeline order inside nerd-dictation (see nerd-dictation.py ~L1386):
      #   1. Vosk emits raw text for the current utterance.
      #   2. process_text() applies --full-sentence: capitalize the first
      #      word. (That's ALL it does; the name is misleading -- it does
      #      NOT append a period, does NOT handle multi-sentence commits,
      #      does NOT insert separators between commits.)
      #   3. nerd_dictation_process() (this callback) runs.
      #   4. The diff between our returned text and text_prev is typed
      #      (with a prefix-match optimisation) via YDOTOOL.
      #
      # So *every* visible bit of formatting besides a single capital on
      # the first word is up to us here.
      import re

      _BLACKLIST          = ${blacklistPython}
      _ADD_LEADING_SPACE  = ${addLeadingSpaceLit}
      _ADD_TRAILING_PERIOD = ${addTrailingPeriodLit}
      _QUESTION_HEURISTIC = ${questionHeuristicLit}
      _VERBAL_PUNCTUATION = ${verbalPunctuationLit}
      _QUESTION_STARTERS  = ${questionStartersPython}

      # --- Verbal punctuation commands ---------------------------------
      # Explicit dictation commands: user says "question mark" and it
      # becomes "?". Regex order matters: longer phrases ("exclamation
      # point") must be tried before shorter ones ("point") to avoid
      # partial matches. Each pattern is anchored with word boundaries so
      # "commander" doesn't get its "comma" lopped off.
      #
      # Vosk transcribes verbal commands as normal English words before
      # this callback sees them, so all we do is substitute regex-for-
      # regex. The callback is called on growing partials, so during the
      # phrase's utterance we may briefly see "question mar" in the buffer
      # -- harmless, diff-typer erases it once the full phrase arrives
      # and the substitution fires.
      _VERBAL_SUBS = [
          # Sentence-enders: absorb any preceding space AND the auto-
          # appended period later, so "what time is it question mark"
          # ends up "what time is it?" rather than "what time is it ?."
          (re.compile(r"\s*\bquestion marks?\b\s*\.?", re.IGNORECASE), "?"),
          (re.compile(r"\s*\bexclamation (?:mark|point)s?\b\s*\.?", re.IGNORECASE), "!"),
          (re.compile(r"\s*\bfull stops?\b\s*\.?", re.IGNORECASE), "."),
          (re.compile(r"\s*\bperiods?\b\s*\.?", re.IGNORECASE), "."),
          # Mid-sentence punctuation: replace in place with no leading
          # whitespace absorption (Vosk already has the space in front).
          (re.compile(r"\s*\bsemicolons?\b", re.IGNORECASE), ";"),
          (re.compile(r"\s*\bcolons?\b", re.IGNORECASE), ":"),
          (re.compile(r"\s*\bcommas?\b", re.IGNORECASE), ","),
          # Structural:
          (re.compile(r"\s*\bnew paragraphs?\b\s*\.?", re.IGNORECASE), "\n\n"),
          (re.compile(r"\s*\bnew lines?\b\s*\.?", re.IGNORECASE), "\n"),
      ]

      _QUESTION_START_RE = re.compile(r"^\s*([A-Za-z']+)")

      # Strip blacklist words when they appear as the final token, whether
      # or not they have leading whitespace (the old regex required \s+
      # prefix, which missed the common case of Vosk hallucinating a lone
      # "The" at end-of-stream). The trailing \W* preserves any punctuation
      # that was already on the word -- so "Hello the." becomes "Hello.",
      # not "Hello".
      _TRAIL_RE = re.compile(r"(?:^|\s+)([A-Za-z']+)(\W*)$")

      # Regex for "does the text already end with a sentence-ending
      # punctuation mark?" -- used to avoid doubling up periods.
      _ENDS_WITH_PUNCT = re.compile(r"[.!?,;:]\s*$")

      def nerd_dictation_process(text: str) -> str:
          # 1. Strip blacklist words from the tail, possibly repeatedly
          #    (Vosk occasionally emits "the the" at tail-of-stream).
          while True:
              m = _TRAIL_RE.search(text)
              if m and m.group(1).lower() in _BLACKLIST:
                  text = text[:m.start()] + m.group(2)
                  continue
              break

          # After stripping, text may be only whitespace or empty. Don't
          # type a spurious " ." from pure hallucination.
          stripped = text.strip()
          if not stripped:
              return ""

          # 2. Verbal punctuation commands. Apply before auto-period so the
          #    explicit user choice wins: if they said "question mark",
          #    we don't then also append a period.
          if _VERBAL_PUNCTUATION:
              for pat, repl in _VERBAL_SUBS:
                  text = pat.sub(repl, text)
              # Substitution can leave internal double spaces.
              text = re.sub(r"  +", " ", text).strip()
              if not text:
                  return ""

          # 3. Trailing sentence punctuation. Vosk / --full-sentence don't
          #    add any sentence-end punctuation, and nerd-dictation's
          #    "commit" boundary (silence > ~250 ms) correlates strongly
          #    with human sentence boundaries in practice. Default to "."
          #    but upgrade to "?" when the heuristic thinks this looks
          #    like a question -- Vosk has no prosody/intonation model,
          #    so this is the best we can do for question marks without
          #    the user saying "question mark" explicitly.
          if _ADD_TRAILING_PERIOD and not _ENDS_WITH_PUNCT.search(text):
              end = "."
              if _QUESTION_HEURISTIC:
                  m = _QUESTION_START_RE.match(text)
                  if m and m.group(1).lower() in _QUESTION_STARTERS:
                      end = "?"
              text = text + end

          # 3. Leading space. Between commits, nerd-dictation's diff-typer
          #    resets text_prev to "" and then types our string verbatim,
          #    with no separator inserted -- so "dictation" + "It seems" ends
          #    up typed as "dictationIt seems". Prepending a space forces a
          #    visible gap.
          #
          #    Trade-off: the *very first* commit of a session also gets a
          #    leading space. For dictation started in the middle of an
          #    existing document (the common case) this is correct. For
          #    dictation started at column 0 of an empty file it looks like
          #    one stray space that the user may want to delete. Acceptable.
          if _ADD_LEADING_SPACE:
              text = " " + text

          return text
    '';

  # Fetch the configured Vosk model into /nix/store (verified by SHA256).
  modelDrv =
    let m = models.${cfg.model}; in
    pkgs.fetchzip {
      name = "vosk-model-${cfg.model}";
      inherit (m) url hash;
      stripRoot = true;
    };

  # Shared begin args between the daemon service and the cold-start toggle.
  # The daemon also appends --suspend-on-start and --timeout=0 so it doesn't
  # auto-exit on silence and never starts pw-cat until the user resumes it.
  beginArgs = [
    "--cookie=%t/nerd-dictation.cookie"   # %t = $XDG_RUNTIME_DIR (systemd)
    "--vosk-model-dir=${modelDrv}"
    "--simulate-input-tool=${cfg.inputTool}"
    "--input=${cfg.input}"
  ]
  ++ lib.optional (cfg.trailingWordBlacklist != [ ]) "--config=${userConfig}"
  ++ lib.optional cfg.numbersAsDigits "--numbers-as-digits"
  ++ lib.optional cfg.fullSentence    "--full-sentence"
  ++ lib.optional cfg.continuous      "--continuous"
  ++ lib.optional cfg.deferOutput     "--defer-output"
  ++ cfg.extraArgs;

  # ---------------------------------------------------------------------------
  # Toggle script.
  #
  # Two modes depending on cfg.daemon:
  #
  #   * daemon=true (default): the nerd-dictation process is already running
  #     (started by the systemd user service below) in "suspended" state, so
  #     the model is loaded and pw-cat is NOT capturing. The toggle just
  #     flips between suspend and resume via SIGUSR1/SIGCONT. First press is
  #     instant -- there is no 6+ second Vosk model-load wait, and no audio
  #     is dropped due to pipe-buffer overflow during load. A state file in
  #     $XDG_RUNTIME_DIR tracks which direction we're going next.
  #
  #   * daemon=false: cold start per dictation. The first press calls
  #     `nerd-dictation begin`, the second calls `nerd-dictation end`. This
  #     has no resident-RAM cost but suffers the 6+ second model-load
  #     latency, during which the user's first words are lost -- the pw-cat
  #     -> python pipe buffer (64 KiB = ~0.7 s at 44.1 kHz s16) fills up
  #     before Vosk is ready to consume it.
  # ---------------------------------------------------------------------------
  toggleScript = pkgs.writeShellApplication {
    name = "nerd-dictation-toggle";
    runtimeInputs = [ nerd-dictation pkgs.ydotool pkgs.procps pkgs.libnotify pkgs.coreutils ];
    text = ''
      set +e
      RUNTIME_DIR="''${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
      STATE_FILE="$RUNTIME_DIR/nerd-dictation.recording"
      COOKIE="$RUNTIME_DIR/nerd-dictation.cookie"

      # Release hotkey modifiers so a still-depressed Super (from the
      # Mod+Comma trigger) can't turn subsequent Vosk-typed letters into
      # niri window-management shortcuts. Keycodes:
      #   29=LCtrl 97=RCtrl 42=LShift 54=RShift
      #   56=LAlt 100=RAlt 125=LSuper 126=RSuper
      ydotool key 29:0 97:0 42:0 54:0 56:0 100:0 125:0 126:0 2>/dev/null || true

      ${if cfg.daemon then ''
        # ---- daemon mode ---------------------------------------------------
        if [ ! -e "$COOKIE" ]; then
          ${lib.optionalString cfg.notify ''
            notify-send -t 2000 -a nerd-dictation "nerd-dictation" \
              "⚠ daemon not running; start with: systemctl --user start nerd-dictation"
          ''}
          exit 1
        fi

        if [ -e "$STATE_FILE" ]; then
          nerd-dictation suspend --cookie="$COOKIE"
          rm -f "$STATE_FILE"
          ${lib.optionalString cfg.notify ''
            notify-send -t 1000 -a nerd-dictation "nerd-dictation" "◼ stopped"
          ''}
        else
          nerd-dictation resume --cookie="$COOKIE"
          : > "$STATE_FILE"
          ${lib.optionalString cfg.notify ''
            notify-send -t 1000 -a nerd-dictation "nerd-dictation" "● listening"
          ''}
        fi
      '' else ''
        # ---- cold-start mode ----------------------------------------------
        if pgrep -f 'nerd-dictation.py.*begin' >/dev/null 2>&1; then
          nerd-dictation end --cookie="$COOKIE"
          ${lib.optionalString cfg.notify ''
            notify-send -t 1000 -a nerd-dictation "nerd-dictation" "◼ stopped"
          ''}
          exit 0
        fi

        ${lib.optionalString cfg.notify ''
          notify-send -t 2000 -a nerd-dictation "nerd-dictation" \
            "⏳ loading model (~7 s)..."
        ''}

        exec nerd-dictation begin \
          ${lib.escapeShellArgs beginArgs} \
          ${lib.optionalString (cfg.timeout != null)
              (lib.escapeShellArg "--timeout=${toString cfg.timeout}")}
      ''}
    '';
  };

in
{
  key = "nixcfg/programs/nerd-dictation";

  options.nixcfg.programs.nerd-dictation = {
    enable = lib.mkEnableOption ''
      nerd-dictation -- offline, low-latency streaming speech-to-text based on
      the VOSK/Kaldi engine. See https://github.com/ideasman42/nerd-dictation.
    '';

    daemon = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Keep a pre-warmed nerd-dictation process running from session start
        (via a systemd user service) so the Vosk model is always loaded and
        toggles are instant. The process sits idle in "suspended" state
        until the toggle script sends it SIGCONT; no audio is captured and
        no CPU is used while suspended, but the model stays resident --
        ~5 GB for the full en-us-0.22 model, ~120 MB for the lgraph
        variant, ~50 MB for the small model.

        When false, each toggle cold-starts nerd-dictation, which takes
        ~6-8 s to load the full model and drops the first ~5 seconds of
        speech because the pw-cat -> python pipe buffer fills during load.
      '';
    };

    model = lib.mkOption {
      type = lib.types.enum (lib.attrNames models);
      default = "small-en-us-0_15";
      description = ''
        Which Vosk model to install. The small model streams with sub-second
        latency on CPU and is the right default for real-time dictation.
        Update modules/programs/nerd-dictation/models.nix to add more.
      '';
    };

    inputTool = lib.mkOption {
      type = lib.types.enum [ "YDOTOOL" "XDOTOOL" "WTYPE" "STDOUT" ];
      default = "YDOTOOL";
      description = ''
        Which tool to use for typing transcribed text. YDOTOOL works anywhere
        on Wayland (requires the ydotoold daemon -- enabled automatically);
        XDOTOOL only works on X11; WTYPE is a lightweight Wayland alternative.
        STDOUT just prints to stdout (useful for piping / debugging).
      '';
    };

    input = lib.mkOption {
      type = lib.types.enum [ "PAREC" "SOX" "PW-CAT" ];
      default = "PW-CAT";
      description = ''
        Which utility nerd-dictation uses to capture audio. PW-CAT talks
        directly to PipeWire (recommended); PAREC uses the PulseAudio
        compatibility layer; SOX uses ALSA.
      '';
    };

    timeout = lib.mkOption {
      type = lib.types.nullOr lib.types.float;
      default = 3.0;
      example = null;
      description = ''
        Seconds of silence that auto-ends dictation without an explicit
        `nerd-dictation end` call. Set to null to disable (toggle-only).
        Ignored when daemon=true -- the daemon uses suspend instead of
        exit, and silence never triggers shutdown (you always stop
        manually via the toggle).
      '';
    };

    numbersAsDigits = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Convert spoken numbers ("three hundred forty two") to digits ("342").
      '';
    };

    fullSentence = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        nerd-dictation's `--full-sentence`. Misleadingly named: this only
        capitalizes the first character of each commit (see
        nerd-dictation.py ~L854). It does NOT append a period, does NOT
        distinguish commits from mid-sentence partials, and does NOT
        insert separators between commits -- so by itself you get output
        like "First commitSecond commit" with no space/period between
        them. The `addLeadingSpace` and `addTrailingPeriod` options
        compensate for this.
      '';
    };

    addLeadingSpace = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Prepend a space to every committed utterance. Without this, Vosk's
        pause-based commit boundary results in "...dictationIt seems..."
        (two consecutive commits typed flush against each other). The cost
        is one stray leading space if dictation is started at the very
        first column of an empty document -- easily deleted.
      '';
    };

    addTrailingPeriod = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Append a period to every committed utterance unless it already
        ends in sentence-ending punctuation. Vosk's commit boundary is
        ~250 ms of silence, which tracks human sentence boundaries well
        enough in practice that one period per commit gets close to
        correctly-punctuated output. During a long utterance, you'll see
        the period flicker at the end of each partial and then move as
        more words are recognized (the diff-typer erases and retypes) --
        this is annoying but harmless.
      '';
    };

    questionHeuristic = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        When `addTrailingPeriod` would otherwise append "." at end of a
        commit, use "?" instead if the first word of the commit is a
        question starter (what/where/when/why/how/who/do/does/did/is/
        are/etc.; see `questionStarters`). Vosk is an acoustic-only ASR
        with no prosody model -- it cannot hear the difference between
        "are you ready" and "are you ready?" -- so this heuristic is
        the best available alternative to the user explicitly saying
        "question mark" (see `verbalPunctuation`).

        False positives happen: sentences like "How I did it was ..."
        start with a question word but aren't questions, so they'll get
        "?". Trade-off is worth it for most conversational dictation.
      '';
    };

    questionStarters = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "who" "what" "when" "where" "why" "how" "which" "whose" "whom"
        "is" "are" "was" "were" "am"
        "do" "does" "did"
        "has" "have" "had"
        "can" "could" "will" "would" "should" "shall"
        "may" "might" "must"
      ];
      description = ''
        Sentence-initial words that trigger "?" instead of "." at end of
        commit (case-insensitive). Only used when `questionHeuristic` is
        true. Entries should be lowercase; the matcher lowercases the
        candidate word before lookup.
      '';
    };

    verbalPunctuation = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Rewrite spoken punctuation commands into the corresponding
        glyphs, so "what time is it question mark" becomes "What time
        is it?". Applied before the auto-period/auto-question heuristic,
        so an explicit verbal command always wins over the heuristic.

        Recognized phrases (case-insensitive, word-bounded so
        "commander" is not affected):
          "question mark"                -> ?
          "exclamation mark" / "point"   -> !
          "period" / "full stop"         -> .
          "comma"                        -> ,
          "colon"                        -> :
          "semicolon"                    -> ;
          "new paragraph"                -> two newlines
          "new line"                     -> one newline

        Caveat: this is a raw text substitution, so if you ever want to
        *literally* say the word "comma" or "period" etc. (e.g.
        discussing grammar) you cannot when this is enabled. Turn off
        per-session by disabling this option globally, or draft such
        passages with Mod+Period (whisper) which transcribes literally.
      '';
    };

    continuous = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Commit recognized text at each pause so later speech can't cause
        Vosk to rewrite earlier words. Without this, the entire session's
        audio stays in the decoding lattice and lattice-rescoring (active
        on the full en-us-0.22 model) can replace a correct earlier
        transcription with a globally-higher-probability but semantically
        wrong one -- you see this as typed text being backspaced and
        retyped into something worse. Strongly recommended for large
        models; near-free on small models.
      '';
    };

    deferOutput = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Wait until the dictation session ends before typing anything, so
        no text ever gets rewritten. Trades live feedback for stability.
        Functionally equivalent to whisper-dictation's batch-at-release
        behavior. Mutually exclusive with `continuous` (continuous is
        ignored when deferOutput is true).
      '';
    };

    trailingWordBlacklist = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ "the" ];
      example = [ "the" "a" "of" "and" ];
      description = ''
        Strip these words (case-insensitive) if they appear as the final
        token of any committed transcript. Works around a Vosk
        end-of-stream artifact: when audio tails off into silence, the
        acoustic model loses confidence and the language model biases
        toward high-prior words (overwhelmingly "the") to fill the
        resulting gap. Trailing punctuation added by `--full-sentence`
        is preserved -- e.g. "Hello world the." becomes "Hello world."
        Set to [ ] to disable the filter entirely.
      '';
    };

    notify = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Show a desktop notification when starting/stopping dictation via the
        toggle script.
      '';
    };

    extraArgs = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      example = [ "--punctuate-from-previous-timeout" "1.0" ];
      description = ''
        Additional flags passed verbatim to `nerd-dictation begin`.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [
      nerd-dictation
      toggleScript
    ];

    # YDOTOOL backend needs the system daemon + "ydotool" group membership.
    programs.ydotool.enable = lib.mkIf (cfg.inputTool == "YDOTOOL") true;
    users.users.${userParams.username}.extraGroups =
      lib.optional (cfg.inputTool == "YDOTOOL") "ydotool";

    # Pre-warmed daemon. Loads the model at session start so Mod+Comma is
    # instant. `--suspend-on-start` holds the process in a paused state
    # where pw-cat isn't running and no audio is captured -- the toggle
    # sends SIGCONT to resume and SIGUSR1 to re-suspend.
    # Pre-warmed daemon. IMPORTANT: NixOS does NOT restart systemd --user
    # services on rebuild. The system-level `nixos-rebuild switch` only
    # auto-restarts changed `systemd.services.*` (system) units. For user
    # units we drop a drop-in into the activation that opts us into
    # automatic restart -- see `systemd.user.startServices` (which also
    # runs `systemctl --user daemon-reload`) plus `X-RestartIfChanged` on
    # the unit itself. Without this, when you edit the user config or
    # trailingWordBlacklist and rebuild, the new config.py lands in the
    # store but the in-memory daemon keeps using the *previous* config
    # path captured by its own cmdline -- dictation silently runs
    # yesterday's code until you reboot or `systemctl --user restart`.
    systemd.user.services.nerd-dictation = lib.mkIf cfg.daemon {
      description = "nerd-dictation (Vosk) -- pre-warmed dictation daemon";
      wantedBy = [ "default.target" ];
      # Depend on the audio stack being up so pw-cat can link on resume.
      after = [ "pipewire.service" ];

      serviceConfig = {
        Type = "simple";
        ExecStart = lib.concatStringsSep " " ([
          (lib.getExe nerd-dictation)
          "begin"
          "--suspend-on-start"
          "--timeout=0"
        ] ++ beginArgs);
        Restart = "on-failure";
        RestartSec = 3;
        # A paused en-us-0.22 resident image is ~5 GB. That's the one
        # real cost of daemon mode; lgraph / small models are far smaller.
      };
    };

  };
}

# Caveat on systemd --user units: NixOS's `nixos-rebuild switch` does NOT
# auto-restart them (only system-level systemd.services.* are). After
# changing any option that reshapes the daemon's cmdline --
# trailingWordBlacklist, addLeadingSpace, addTrailingPeriod, model,
# extraArgs, etc. -- the new config.py / unit file will be in /etc/
# but the running daemon will still be executing the previous one.
# Run:
#
#   systemctl --user daemon-reload
#   systemctl --user restart nerd-dictation.service
#
# or log out and back in. `systemctl --user status nerd-dictation` prints
# the cmdline; cross-check --config= against `ls /nix/store/*nerd-dictation-config.py`
# to see whether a restart is still owed. A generic nixpkgs option to
# opt user units into rebuild-restart has been discussed (NixOS/nixpkgs#81138)
# but is not landed as of the revision currently pinned in this flake.
