#!/usr/bin/env bash

sudo mkdir -p /mnt/ellis/Backups/x1c-home
sudo chown erahhal:users /mnt/ellisBackups/x1c-home

wget https://raw.githubusercontent.com/rubo77/rsync-homedir-excludes/master/rsync-homedir-excludes.txt -O /var/tmp/ignorelist

sudo rsync -aP \
  --exclude=.BitwigStudio \
  --exclude="VirtualBox VMs" \
  --exclude=Android \
  --exclude=.android \
  --exclude=.gradle \
  --exclude=.config/Signal \
  --exclude=.local/share/Steam \
  --exclude=.local/share/bottles \
  --exclude=.local/state/nix \
  --exclude=.local/state/home-manager \
  --exclude-from=/var/tmp/ignorelist \
  --progress /home/$USER /mnt/ellis/Backups/x1c-home
