#!/usr/bin/env bash

NAME="pulse-secure"

packages=("vim" "libnss3-tools" "net-tools" "libglib2.0-0" "libgtkmm-3.0-1v5" "libwebkit2gtk-4.0-37" "acl")
package_list=""
for package in ${packages[@]}; do
    package_list="$package_list $package"
done

if ! distrobox list | grep -q $NAME; then
    distrobox create --name $NAME -i ubuntu:22.04 --volume /run/dbus:/run/dbus --init-hooks "apt install -y $package_list"
fi
distrobox enter $NAME -- "chsh -s /bin/bash"

if ! distrobox enter $NAME -- apt --installed list | grep pulsesecure; then
    distrobox enter $NAME -- "sudo dpkg -i ~/Code/nixcfg-nflx/profiles/pulse-secure/ps-pulse-linux-22.2r1.0-b1295-64bit-installer.deb"
    ## Doesn't seem to actually run pulsesecure using sudo
    distrobox enter $NAME -- "distrobox-export --service pulsesecure --sudo"
fi
