#!/usr/bin/env bash

SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

HOST=$(hostname -s)

pushd .
echo kanshi -c "${DIR}/hosts/${HOST}/kanshi-gaming.config"
nohup kanshi -c "${DIR}/hosts/${HOST}/kanshi-gaming.config" > /dev/null 2>&1 &
serverPID=$!
sleep 3
kill $serverPID
popd

export __NV_PRIME_RENDER_OFFLOAD=1
export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export __VK_LAYER_NV_optimus=NVIDIA_only

echo "$@" >> ~/start-game.log
"$@"

# systemctl --user restart kanshi
