#!/usr/bin/env bash

fio --name TEST --eta-newline=5s --filename=/mnt/ellis/fio-tempfile.dat --rw=read --size=500m --io_size=10g --blocksize=1024k --ioengine=libaio --fsync=10000 --iodepth=32 --direct=1 --numjobs=1 --runtime=60 --group_reporting
rm /mnt/ellis/fio-tempfile.dat
