# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/076a7e05-8dcc-46c8-ae04-f640889808bc";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1B5B-E118";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/428254a4-4b2f-4a0a-a222-7b444f3b7c6b"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
